// Generated by gencpp from file odom_data/odom_data.msg
// DO NOT EDIT!


#ifndef ODOM_DATA_MESSAGE_ODOM_DATA_H
#define ODOM_DATA_MESSAGE_ODOM_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/PoseWithCovariance.h>

namespace odom_data
{
template <class ContainerAllocator>
struct odom_data_
{
  typedef odom_data_<ContainerAllocator> Type;

  odom_data_()
    : header()
    , pose()
    , odom_state(0)
    , track_count(0)
    , lost_count(0)
    , Scale_Inited(false)  {
    }
  odom_data_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pose(_alloc)
    , odom_state(0)
    , track_count(0)
    , lost_count(0)
    , Scale_Inited(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::PoseWithCovariance_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef uint8_t _odom_state_type;
  _odom_state_type odom_state;

   typedef uint32_t _track_count_type;
  _track_count_type track_count;

   typedef uint8_t _lost_count_type;
  _lost_count_type lost_count;

   typedef uint8_t _Scale_Inited_type;
  _Scale_Inited_type Scale_Inited;





  typedef boost::shared_ptr< ::odom_data::odom_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::odom_data::odom_data_<ContainerAllocator> const> ConstPtr;

}; // struct odom_data_

typedef ::odom_data::odom_data_<std::allocator<void> > odom_data;

typedef boost::shared_ptr< ::odom_data::odom_data > odom_dataPtr;
typedef boost::shared_ptr< ::odom_data::odom_data const> odom_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::odom_data::odom_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::odom_data::odom_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace odom_data

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'odom_data': ['/home/te6000-16/catkin_ws/src/odom_data/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::odom_data::odom_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::odom_data::odom_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::odom_data::odom_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::odom_data::odom_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::odom_data::odom_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::odom_data::odom_data_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::odom_data::odom_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a42503faf40304990cfbedd78df4a9ec";
  }

  static const char* value(const ::odom_data::odom_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa42503faf4030499ULL;
  static const uint64_t static_value2 = 0x0cfbedd78df4a9ecULL;
};

template<class ContainerAllocator>
struct DataType< ::odom_data::odom_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "odom_data/odom_data";
  }

  static const char* value(const ::odom_data::odom_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::odom_data::odom_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
geometry_msgs/PoseWithCovariance pose\n\
uint8 odom_state   \n\
#0	NO IMAGE\n\
#1  INITING\n\
#2	TRACK OK\n\
#3	LOST\n\
uint32 track_count\n\
uint8  lost_count\n\
bool Scale_Inited\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseWithCovariance\n\
# This represents a pose in free space with uncertainty.\n\
\n\
Pose pose\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::odom_data::odom_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::odom_data::odom_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pose);
      stream.next(m.odom_state);
      stream.next(m.track_count);
      stream.next(m.lost_count);
      stream.next(m.Scale_Inited);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct odom_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::odom_data::odom_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::odom_data::odom_data_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseWithCovariance_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "odom_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.odom_state);
    s << indent << "track_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.track_count);
    s << indent << "lost_count: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lost_count);
    s << indent << "Scale_Inited: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Scale_Inited);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ODOM_DATA_MESSAGE_ODOM_DATA_H
